<a href="https://colab.research.google.com/github/hiagojacobs/Planar-Arm-6-joints/blob/main/Trabajo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Trabajo 1 - Cinemática Inversa Planar Arm 6 articulaciones




In [1]:
import numpy as np
from sympy import *
import math

np.set_printoptions(suppress=True)

In [2]:
#cinematica direta

theta1 = Symbol("theta1")
theta2 = Symbol("theta2")
theta3 = Symbol("theta3")
theta4 = Symbol("theta4")
theta5 = Symbol("theta5")
theta6 = Symbol("theta6")

l1 = Symbol("l1")
l2 = Symbol("l2")
l3 = Symbol("l3")
l4 = Symbol("l4")
l5 = Symbol("l5")
l6 = Symbol("l6")

T1 = Matrix([ [cos(theta1), -sin(theta1), 0, l1*cos(theta1)],
              [sin(theta1), cos(theta1), 0, l1*sin(theta1)],
              [0, 0, 1, 0],
              [0, 0, 0, 1]
            ])

T2 = Matrix([ [cos(theta2), -sin(theta2), 0, l2*cos(theta2)],
              [sin(theta2), cos(theta2), 0, l2*sin(theta2)],
              [0, 0, 1, 0],
              [0, 0, 0, 1]
            ])
T3 = Matrix([ [cos(theta3), -sin(theta3), 0, l3*cos(theta3)],
              [sin(theta3), cos(theta3), 0, l3*sin(theta3)],
              [0, 0, 1, 0],
              [0, 0, 0, 1]
            ])

T4 = Matrix([ [cos(theta4), -sin(theta4), 0, l4*cos(theta4)],
              [sin(theta4), cos(theta4), 0, l4*sin(theta4)],
              [0, 0, 1, 0],
              [0, 0, 0, 1]
            ])
T5 = Matrix([ [cos(theta5), -sin(theta5), 0, l5*cos(theta5)],
              [sin(theta5), cos(theta5), 0, l5*sin(theta5)],
              [0, 0, 1, 0],
              [0, 0, 0, 1]
            ])
T6 = Matrix([ [cos(theta6), -sin(theta6), 0, l6*cos(theta6)],
              [sin(theta6), cos(theta6), 0, l6*sin(theta6)],
              [0, 0, 1, 0],
              [0, 0, 0, 1]
            ])


T = T1*T2*T3*T4*T5*T6

print(T[3])
print(T[7])


l1*cos(theta1) - l2*sin(theta1)*sin(theta2) + l2*cos(theta1)*cos(theta2) + l3*(-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*cos(theta3) + l3*(-sin(theta1)*cos(theta2) - sin(theta2)*cos(theta1))*sin(theta3) + l4*(-(-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*sin(theta3) + (-sin(theta1)*cos(theta2) - sin(theta2)*cos(theta1))*cos(theta3))*sin(theta4) + l4*((-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*cos(theta3) + (-sin(theta1)*cos(theta2) - sin(theta2)*cos(theta1))*sin(theta3))*cos(theta4) + l5*((-(-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*sin(theta3) + (-sin(theta1)*cos(theta2) - sin(theta2)*cos(theta1))*cos(theta3))*sin(theta4) + ((-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*cos(theta3) + (-sin(theta1)*cos(theta2) - sin(theta2)*cos(theta1))*sin(theta3))*cos(theta4))*cos(theta5) + l5*((-(-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*sin(theta3) + (-sin(theta1)*cos(theta2) - sin(theta2)*cos(theta1))*cos(theta3))*cos(theta4) - ((-sin(theta1)*

In [3]:
#defición en espacion

# Acessando os termos de translação de T
x = T[0, 3]
y = T[1, 3]

# Substituindo os valores numéricos
x = x.subs([(l1, 100), (l2, 100), (l3, 100), (l4, 100), (l5, 100), (l6, 100),
            (theta1, 0.0), (theta2, 0.0), (theta3, 0.0), (theta4, 0.0), (theta5, 0.0), (theta6, 0.0)])

y = y.subs([(l1, 100), (l2, 100), (l3, 100), (l4, 100), (l5, 100), (l6, 100),
            (theta1, 0.0), (theta2, 0.0), (theta3, 0.0), (theta4, 0.0), (theta5, 0.0), (theta6, 0.0)])

print("Posição final x:", x)
print("Posição final y:", y)

Posição final x: 600
Posição final y: 0


In [4]:
#matriz Jacobiana

x = T[3]
y = T[7]

a00 = simplify(diff(x, theta1)) #terminos de la matriz
a01 = simplify(diff(x, theta2))
a02 = simplify(diff(x, theta3))
a03 = simplify(diff(x, theta4))
a04 = simplify(diff(x, theta5))
a05 = simplify(diff(x, theta6))

a10 = simplify(diff(y, theta1))
a11 = simplify(diff(y, theta2))
a12 = simplify(diff(y, theta3))
a13 = simplify(diff(y, theta4))
a14 = simplify(diff(y, theta5))
a15 = simplify(diff(y, theta6))

Jacobs_generic = [ [a00,a01,a02,a03,a04,a05],
                   [a10,a11,a12,a13,a14,a15]
]

print(Jacobs_generic[0][0])
print(Jacobs_generic[0][1])
print(Jacobs_generic[0][2])
print(Jacobs_generic[0][3])
print(Jacobs_generic[0][4])
print(Jacobs_generic[0][5])
print(Jacobs_generic[1][0])
print(Jacobs_generic[1][1])
print(Jacobs_generic[1][2])
print(Jacobs_generic[1][3])
print(Jacobs_generic[1][4])
print(Jacobs_generic[1][5])

-l1*sin(theta1) - l2*sin(theta1)*cos(theta2) - l2*sin(theta2)*cos(theta1) - l3*sin(theta3)*cos(theta1 + theta2) - l3*sin(theta1 + theta2)*cos(theta3) - l4*sin(theta4)*cos(theta1 + theta2 + theta3) - l4*sin(theta1 + theta2 + theta3)*cos(theta4) - l5*sin(theta5)*cos(theta1 + theta2 + theta3 + theta4) - l5*sin(theta1 + theta2 + theta3 + theta4)*cos(theta5) - l6*sin(theta6)*cos(theta1 + theta2 + theta3 + theta4 + theta5) - l6*sin(theta1 + theta2 + theta3 + theta4 + theta5)*cos(theta6)
-l2*sin(theta1)*cos(theta2) - l2*sin(theta2)*cos(theta1) - l3*sin(theta3)*cos(theta1 + theta2) - l3*sin(theta1 + theta2)*cos(theta3) - l4*sin(theta4)*cos(theta1 + theta2 + theta3) - l4*sin(theta1 + theta2 + theta3)*cos(theta4) - l5*sin(theta5)*cos(theta1 + theta2 + theta3 + theta4) - l5*sin(theta1 + theta2 + theta3 + theta4)*cos(theta5) - l6*sin(theta6)*cos(theta1 + theta2 + theta3 + theta4 + theta5) - l6*sin(theta1 + theta2 + theta3 + theta4 + theta5)*cos(theta6)
-l3*sin(theta3)*cos(theta1 + theta2) - l3*sin

In [5]:
#funcion de substituición / calculando jacobiana

def calc_jacobian(Jacobs, theta1_desired, theta2_desired, theta3_desired, theta4_desired, theta5_desired, theta6_desired, l1_value, l2_value, l3_value, l4_value, l5_value, l6_value):
  Jacobs [0][0] = Jacobs [0][0].subs(theta1, theta1_desired)
  Jacobs [0][1] = Jacobs [0][1].subs(theta1, theta1_desired)
  Jacobs [0][2] = Jacobs [0][2].subs(theta1, theta1_desired)
  Jacobs [0][3] = Jacobs [0][3].subs(theta1, theta1_desired)
  Jacobs [0][4] = Jacobs [0][4].subs(theta1, theta1_desired)
  Jacobs [0][5] = Jacobs [0][5].subs(theta1, theta1_desired)
  Jacobs [1][0] = Jacobs [1][0].subs(theta1, theta1_desired)
  Jacobs [1][1] = Jacobs [1][1].subs(theta1, theta1_desired)
  Jacobs [1][2] = Jacobs [1][2].subs(theta1, theta1_desired)
  Jacobs [1][3] = Jacobs [1][3].subs(theta1, theta1_desired)
  Jacobs [1][4] = Jacobs [1][4].subs(theta1, theta1_desired)
  Jacobs [1][5] = Jacobs [1][5].subs(theta1, theta1_desired)

  Jacobs [0][0] = Jacobs [0][0].subs(theta2, theta2_desired)
  Jacobs [0][1] = Jacobs [0][1].subs(theta2, theta2_desired)
  Jacobs [0][2] = Jacobs [0][2].subs(theta2, theta2_desired)
  Jacobs [0][3] = Jacobs [0][3].subs(theta2, theta2_desired)
  Jacobs [0][4] = Jacobs [0][4].subs(theta2, theta2_desired)
  Jacobs [0][5] = Jacobs [0][5].subs(theta2, theta2_desired)
  Jacobs [1][0] = Jacobs [1][0].subs(theta2, theta2_desired)
  Jacobs [1][1] = Jacobs [1][1].subs(theta2, theta2_desired)
  Jacobs [1][2] = Jacobs [1][2].subs(theta2, theta2_desired)
  Jacobs [1][3] = Jacobs [1][3].subs(theta2, theta2_desired)
  Jacobs [1][4] = Jacobs [1][4].subs(theta2, theta2_desired)
  Jacobs [1][5] = Jacobs [1][5].subs(theta2, theta2_desired)

  Jacobs [0][0] = Jacobs [0][0].subs(theta3, theta3_desired)
  Jacobs [0][1] = Jacobs [0][1].subs(theta3, theta3_desired)
  Jacobs [0][2] = Jacobs [0][2].subs(theta3, theta3_desired)
  Jacobs [0][3] = Jacobs [0][3].subs(theta3, theta3_desired)
  Jacobs [0][4] = Jacobs [0][4].subs(theta3, theta3_desired)
  Jacobs [0][5] = Jacobs [0][5].subs(theta3, theta3_desired)
  Jacobs [1][0] = Jacobs [1][0].subs(theta3, theta3_desired)
  Jacobs [1][1] = Jacobs [1][1].subs(theta3, theta3_desired)
  Jacobs [1][2] = Jacobs [1][2].subs(theta3, theta3_desired)
  Jacobs [1][3] = Jacobs [1][3].subs(theta3, theta3_desired)
  Jacobs [1][4] = Jacobs [1][4].subs(theta3, theta3_desired)
  Jacobs [1][5] = Jacobs [1][5].subs(theta3, theta3_desired)

  Jacobs [0][0] = Jacobs [0][0].subs(theta4, theta4_desired)
  Jacobs [0][1] = Jacobs [0][1].subs(theta4, theta4_desired)
  Jacobs [0][2] = Jacobs [0][2].subs(theta4, theta4_desired)
  Jacobs [0][3] = Jacobs [0][3].subs(theta4, theta4_desired)
  Jacobs [0][4] = Jacobs [0][4].subs(theta4, theta4_desired)
  Jacobs [0][5] = Jacobs [0][5].subs(theta4, theta4_desired)
  Jacobs [1][0] = Jacobs [1][0].subs(theta4, theta4_desired)
  Jacobs [1][1] = Jacobs [1][1].subs(theta4, theta4_desired)
  Jacobs [1][2] = Jacobs [1][2].subs(theta4, theta4_desired)
  Jacobs [1][3] = Jacobs [1][3].subs(theta4, theta4_desired)
  Jacobs [1][4] = Jacobs [1][4].subs(theta4, theta4_desired)
  Jacobs [1][5] = Jacobs [1][5].subs(theta4, theta4_desired)

  Jacobs [0][0] = Jacobs [0][0].subs(theta5, theta5_desired)
  Jacobs [0][1] = Jacobs [0][1].subs(theta5, theta5_desired)
  Jacobs [0][2] = Jacobs [0][2].subs(theta5, theta5_desired)
  Jacobs [0][3] = Jacobs [0][3].subs(theta5, theta5_desired)
  Jacobs [0][4] = Jacobs [0][4].subs(theta5, theta5_desired)
  Jacobs [0][5] = Jacobs [0][5].subs(theta5, theta5_desired)
  Jacobs [1][0] = Jacobs [1][0].subs(theta5, theta5_desired)
  Jacobs [1][1] = Jacobs [1][1].subs(theta5, theta5_desired)
  Jacobs [1][2] = Jacobs [1][2].subs(theta5, theta5_desired)
  Jacobs [1][3] = Jacobs [1][3].subs(theta5, theta5_desired)
  Jacobs [1][4] = Jacobs [1][4].subs(theta5, theta5_desired)
  Jacobs [1][5] = Jacobs [1][5].subs(theta5, theta5_desired)

  Jacobs [0][0] = Jacobs [0][0].subs(theta6, theta6_desired)
  Jacobs [0][1] = Jacobs [0][1].subs(theta6, theta6_desired)
  Jacobs [0][2] = Jacobs [0][2].subs(theta6, theta6_desired)
  Jacobs [0][3] = Jacobs [0][3].subs(theta6, theta6_desired)
  Jacobs [0][4] = Jacobs [0][4].subs(theta6, theta6_desired)
  Jacobs [0][5] = Jacobs [0][5].subs(theta6, theta6_desired)
  Jacobs [1][0] = Jacobs [1][0].subs(theta6, theta6_desired)
  Jacobs [1][1] = Jacobs [1][1].subs(theta6, theta6_desired)
  Jacobs [1][2] = Jacobs [1][2].subs(theta6, theta6_desired)
  Jacobs [1][3] = Jacobs [1][3].subs(theta6, theta6_desired)
  Jacobs [1][4] = Jacobs [1][4].subs(theta6, theta6_desired)
  Jacobs [1][5] = Jacobs [1][5].subs(theta6, theta6_desired)

  Jacobs [0][0] = Jacobs [0][0].subs(l1, l1_value)
  Jacobs [0][1] = Jacobs [0][1].subs(l1, l1_value)
  Jacobs [0][2] = Jacobs [0][2].subs(l1, l1_value)
  Jacobs [0][3] = Jacobs [0][3].subs(l1, l1_value)
  Jacobs [0][4] = Jacobs [0][4].subs(l1, l1_value)
  Jacobs [0][5] = Jacobs [0][5].subs(l1, l1_value)
  Jacobs [1][0] = Jacobs [1][0].subs(l1, l1_value)
  Jacobs [1][1] = Jacobs [1][1].subs(l1, l1_value)
  Jacobs [1][2] = Jacobs [1][2].subs(l1, l1_value)
  Jacobs [1][3] = Jacobs [1][3].subs(l1, l1_value)
  Jacobs [1][4] = Jacobs [1][4].subs(l1, l1_value)
  Jacobs [1][5] = Jacobs [1][5].subs(l1, l1_value)

  Jacobs [0][0] = Jacobs [0][0].subs(l2, l2_value)
  Jacobs [0][1] = Jacobs [0][1].subs(l2, l2_value)
  Jacobs [0][2] = Jacobs [0][2].subs(l2, l2_value)
  Jacobs [0][3] = Jacobs [0][3].subs(l2, l2_value)
  Jacobs [0][4] = Jacobs [0][4].subs(l2, l2_value)
  Jacobs [0][5] = Jacobs [0][5].subs(l2, l2_value)
  Jacobs [1][0] = Jacobs [1][0].subs(l2, l2_value)
  Jacobs [1][1] = Jacobs [1][1].subs(l2, l2_value)
  Jacobs [1][2] = Jacobs [1][2].subs(l2, l2_value)
  Jacobs [1][3] = Jacobs [1][3].subs(l2, l2_value)
  Jacobs [1][4] = Jacobs [1][4].subs(l2, l2_value)
  Jacobs [1][5] = Jacobs [1][5].subs(l2, l2_value)

  Jacobs [0][0] = Jacobs [0][0].subs(l3, l3_value)
  Jacobs [0][1] = Jacobs [0][1].subs(l3, l3_value)
  Jacobs [0][2] = Jacobs [0][2].subs(l3, l3_value)
  Jacobs [0][3] = Jacobs [0][3].subs(l3, l3_value)
  Jacobs [0][4] = Jacobs [0][4].subs(l3, l3_value)
  Jacobs [0][5] = Jacobs [0][5].subs(l3, l3_value)
  Jacobs [1][0] = Jacobs [1][0].subs(l3, l3_value)
  Jacobs [1][1] = Jacobs [1][1].subs(l3, l3_value)
  Jacobs [1][2] = Jacobs [1][2].subs(l3, l3_value)
  Jacobs [1][3] = Jacobs [1][3].subs(l3, l3_value)
  Jacobs [1][4] = Jacobs [1][4].subs(l3, l3_value)
  Jacobs [1][5] = Jacobs [1][5].subs(l3, l3_value)

  Jacobs [0][0] = Jacobs [0][0].subs(l4, l4_value)
  Jacobs [0][1] = Jacobs [0][1].subs(l4, l4_value)
  Jacobs [0][2] = Jacobs [0][2].subs(l4, l4_value)
  Jacobs [0][3] = Jacobs [0][3].subs(l4, l4_value)
  Jacobs [0][4] = Jacobs [0][4].subs(l4, l4_value)
  Jacobs [0][5] = Jacobs [0][5].subs(l4, l4_value)
  Jacobs [1][0] = Jacobs [1][0].subs(l4, l4_value)
  Jacobs [1][1] = Jacobs [1][1].subs(l4, l4_value)
  Jacobs [1][2] = Jacobs [1][2].subs(l4, l4_value)
  Jacobs [1][3] = Jacobs [1][3].subs(l4, l4_value)
  Jacobs [1][4] = Jacobs [1][4].subs(l4, l4_value)
  Jacobs [1][5] = Jacobs [1][5].subs(l4, l4_value)

  Jacobs [0][0] = Jacobs [0][0].subs(l5, l5_value)
  Jacobs [0][1] = Jacobs [0][1].subs(l5, l5_value)
  Jacobs [0][2] = Jacobs [0][2].subs(l5, l5_value)
  Jacobs [0][3] = Jacobs [0][3].subs(l5, l5_value)
  Jacobs [0][4] = Jacobs [0][4].subs(l5, l5_value)
  Jacobs [0][5] = Jacobs [0][5].subs(l5, l5_value)
  Jacobs [1][0] = Jacobs [1][0].subs(l5, l5_value)
  Jacobs [1][1] = Jacobs [1][1].subs(l5, l5_value)
  Jacobs [1][2] = Jacobs [1][2].subs(l5, l5_value)
  Jacobs [1][3] = Jacobs [1][3].subs(l5, l5_value)
  Jacobs [1][4] = Jacobs [1][4].subs(l5, l5_value)
  Jacobs [1][5] = Jacobs [1][5].subs(l5, l5_value)

  Jacobs [0][0] = Jacobs [0][0].subs(l6, l6_value)
  Jacobs [0][1] = Jacobs [0][1].subs(l6, l6_value)
  Jacobs [0][2] = Jacobs [0][2].subs(l6, l6_value)
  Jacobs [0][3] = Jacobs [0][3].subs(l6, l6_value)
  Jacobs [0][4] = Jacobs [0][4].subs(l6, l6_value)
  Jacobs [0][5] = Jacobs [0][5].subs(l6, l6_value)
  Jacobs [1][0] = Jacobs [1][0].subs(l6, l6_value)
  Jacobs [1][1] = Jacobs [1][1].subs(l6, l6_value)
  Jacobs [1][2] = Jacobs [1][2].subs(l6, l6_value)
  Jacobs [1][3] = Jacobs [1][3].subs(l6, l6_value)
  Jacobs [1][4] = Jacobs [1][4].subs(l6, l6_value)
  Jacobs [1][5] = Jacobs [1][5].subs(l6, l6_value)

  return np.asarray(Jacobs, dtype ="float") #casting

Jacobs_test = Jacobs_generic

print(calc_jacobian(Jacobs_test, 0.0, math.radians(90), 0.0, 0.0, 0.0, 0.0, 100, 100, 100, 100, 100, 100))

[[-500. -500. -400. -300. -200. -100.]
 [ 100.    0.    0.    0.    0.    0.]]


In [6]:
#invertiendo matriz

angles = np.array([0.0, math.radians(90), 0.0, 0.0, 0.0, 0.0])

# Added the missing arguments for lengths l1 to l6 with a value of 100.0 for each
J = calc_jacobian(Jacobs_test, angles[0], angles[1], angles[2], angles[3], angles[4], angles[5], 100.0, 100.0, 100.0, 100.0, 100.0, 100.0)

#Jacobs_inv = np.linalg.inv(J)     # inversa
Jacobs_inv = np.linalg.pinv(J)     # pseudo inversa

print(Jacobs_inv)

[[ 0.          0.01      ]
 [-0.00090909 -0.00454545]
 [-0.00072727 -0.00363636]
 [-0.00054545 -0.00272727]
 [-0.00036364 -0.00181818]
 [-0.00018182 -0.00090909]]


In [7]:
#multiplicando por variación en el espacio

delta_cartesian = np.array([5.0, 0.0])

delta_angles = Jacobs_inv.dot(delta_cartesian)

print(delta_angles)

#sumando por variación

angles = angles + delta_angles

print(angles)


[ 0.         -0.00454545 -0.00363636 -0.00272727 -0.00181818 -0.00090909]
[ 0.          1.56625087 -0.00363636 -0.00272727 -0.00181818 -0.00090909]
